 # Query
query: "1"

# Context file containing TODs
context: './ccat_datacenter_mock/context/context.yaml'

# Telescope info
freq: 'f280'
site: 'so_lat'

# Mapping area footprint
area: './ccat_datacenter_mock/context/geom.fits'

# Output Directory and file name prefix
odir: './ccat_datacenter_mock/maps_deep56'
# Edit prefix as required
prefix: 'mlmap_deep56_d100' 

# Detectors info. null by default
#tods: [::100] # Restrict TOD selections by index
#ntod: 3 # Special case of `tods` above. Implemented as follows: [:ntod]
#nset: 10 # Number of detsets kept
#max-dets: 200 # Maximum dets kept
#wafer: 'w17' # Restrict which wafers are mapped. Can do multiple wafers

# Mapmaking meta
comps: 'T' # 'TQU' #'T'
inject: null
nocal: True # No relcal or abscal
downsample: 1 # Downsample TOD by this factor
tiled: 1 # Tiling boolean (0 or 1)
nmat-dir: './ccat_datacenter_mock/nmats/' # Dir to save or load nmat
nmat: 'corr' # 'corr' or 'uncorr'
maxiter: 500 #500 default # Max number of iterative steps
nmat_mode: 'build' # 'cache', 'build', 'load' or 'save'
center_at: null #'16.0:-2.0'
window: 0.0
inject: null

#Calibration
#No calib fior sim data
nocal: True


# Scripting tools
verbose: False
quiet: True
dump-write: False

